### ISSUE TITLE
Argument is of length 0 for IEEE style

### ISSUE THREAD

**Issue by oskasf** [ropenscilabs/seasl#8]
<details> <summary><strong>Session Info</strong></summary>
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       macOS Big Sur 10.16         
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Europe/London               
 date     2021-05-06                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source                       
 cachem        1.0.4   2021-02-13 [1] standard (@1.0.4)            
 callr         3.6.0   2021-03-28 [1] CRAN (R 4.0.2)               
 cli           2.4.0   2021-04-05 [1] CRAN (R 4.0.2)               
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.2)               
 crul          1.1.0   2021-02-15 [1] CRAN (R 4.0.2)               
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.1)               
 desc          1.3.0   2021-03-05 [1] CRAN (R 4.0.2)               
 devtools      2.4.1   2021-05-05 [1] standard (@2.4.1)            
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.2)               
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)               
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.1)               
 fastmap       1.1.0   2021-01-25 [1] standard (@1.1.0)            
 fs            1.5.0   2020-07-31 [1] standard (@1.5.0)            
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)               
 hoardr        0.5.2   2018-12-02 [1] CRAN (R 4.0.2)               
 htmltools     0.5.1.1 2021-01-22 [1] standard (@0.5.1.1)          
 httpcode      0.3.0   2020-04-10 [1] CRAN (R 4.0.2)               
 knitr         1.31    2021-01-27 [1] standard (@1.31)             
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.2)               
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)               
 memoise       2.0.0   2021-01-26 [1] standard (@2.0.0)            
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.2)               
 pkgload       1.2.1   2021-04-06 [1] CRAN (R 4.0.2)               
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)               
 processx      3.5.1   2021-04-04 [1] CRAN (R 4.0.2)               
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.0.2)               
 purrr         0.3.4   2020-04-17 [1] standard (@0.3.4)            
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)               
 rappdirs      0.3.3   2021-01-31 [1] CRAN (R 4.0.2)               
 remotes       2.3.0   2021-04-01 [1] standard (@2.3.0)            
 rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.2)               
 rmarkdown     2.7     2021-02-19 [1] standard (@2.7)              
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.2)               
 seasl       * 0.2.0   2021-05-06 [1] Github (ropensci/csl@b31f3db)
 sessioninfo   1.1.1   2018-11-05 [1] standard (@1.1.1)            
 testthat      3.0.2   2021-02-14 [1] CRAN (R 4.0.2)               
 usethis       2.0.1   2021-02-10 [1] standard (@2.0.1)            
 withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.2)               
 xfun          0.22    2021-03-11 [1] standard (@0.22)             
 xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.2)               
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)               

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

I have installed all csl files using `seasl::csl_fetch_styles`, yet when running
```r
seasl::csl_style_load(input="ieee")
```
I get the error `Error in if (!is.na(st)) { : argument is of length zero`. This error doesn't appear for other styles such as "apa" etc.

**Comment by sckott** [comment]
thanks, having a look

**Comment by sckott** [comment]
Please try again after reinstalling like `remotes::install_github("ropensci/seasl")` or similar

**Comment by oskasf** [comment]
Ah it works now, thank you!
